# Pysgrid Conda recipe
package:
    name: pysgrid
    version: "0.3.1"

source:
    fn: pyugrid-0.2.0.zip
    url:  https://github.com/pyugrid/pyugrid/archive/develop.zip

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - netcdf4
        - scipy

test:
    imports:
        - pysgrid

about:
    home: https://github.com/jay-hennen/pysgrid
    license: BSD
    summary: 'A Python API to utilize data managed under the structured grid SGRID conventions'
